### ISSUE TITLE
Serial interface initialization error

### ISSUE THREAD

**Issue by orlikom** [lmatula/ha_chint_pm#1]
While trying to run the integration with serial interface I found error in line 317 of __init__.py. The entry.data[CONF_HOST] is not defined for serial inteface and the integration fails to run. I suggest change in lines 317-322 to:
         if entry.data[CONF_HOST] is None:
            port_host = ""
            port_name = str(entry.data[CONF_PORT])
        else:
            port_host = "".join(filter(str.isalnum, entry.data[CONF_HOST]))
            port_name = "".join(filter(str.isalnum, entry.data[CONF_PORT]))

**Comment by lmatula** [comment]
I made changes, plese test latest master commit.
I'm can't test direct serial connetion
