### ISSUE TITLE
[Question] DDSU666 integration

### ISSUE THREAD

**Issue by mvtap** [lmatula/ha_chint_pm#15]
Hello

Do you plan on adding the configuration for the DDSU device? As far as I know is very similar but for one phase only.

Nevertheless good job adding the current integration.

Thank you

**Comment by lmatula** [comment]
Hi,
I'm planing, but currently i havn't enoght time.
And i can't test modbus address mapping.

The plan, move addressis to sensor.py --> SENSOR_DESCRIPTION tuple, this is meaning can configure any modbus meter in future

**Comment by mvtap** [comment]
I can try to help and add the addresses of DDSU666. Can you provide me some kind of guidelines where I should I add that information in your code? You already have the documentation of the device in the docs folder btw
