### ISSUE TITLE
Wrong measured values for DTSU666

### ISSUE THREAD

**Issue by orlikom** [lmatula/ha_chint_pm#2]
The integration provides me a values which are not correctly scaled, e.g. A-phase voltage=2245.0V or A phase current=1675.0 A.
It seems that register values are not scaled properly. I have taken a look into domoticz implementation (see https://github.com/elfabriceu/DTSU666-Modbus/blob/main/plugin.py) and I found that the values should be scaled (and are fine when I apply the scaling factors). I cannot see anything simillar in this  Home Assistant integration...

**Comment by lmatula** [comment]
Witch type of dtsu666 do youe have?

Seems exists multiple modbus implementation

my DTSU666-H is provide right value, but i getted spec of DTSU666-CT, and this type of meter must multiply 0.1.

I'm currently planing make a type select option in config flow

**Comment by orlikom** [comment]
I have got DTSU666.

**Comment by lmatula** [comment]
I'm added multiple type of DTSU666 variant support to config flow.
Becuse i'm have DTSU666-H i'm can't make real test with thist configuration

**Comment by orlikom** [comment]
I cannot add itegration:

Logger: custom_components.chint_pm.config_flow
Source: custom_components/chint_pm/config_flow.py:105
Integration: Chint powermeter DxSU-666-h ([documentation](https://github.com/lmatula/ha_chint_pm), [issues](https://github.com/lmatula/ha_chint_pm/issues))
First occurred: 12:21:37 (19 occurrences)
Last logged: 12:38:33

'meter_type'
Traceback (most recent call last):
  File "/config/custom_components/chint_pm/config_flow.py", line 240, in async_step_setup_serial
    info = await validate_serial_setup(user_input)
  File "/config/custom_components/chint_pm/config_flow.py", line 105, in validate_serial_setup
    match data[CONF_METER_TYPE]:
KeyError: 'meter_type'

**Comment by lmatula** [comment]
do you try remove and re add completly? first step in config flow chose set meter_type config variable
![image](https://user-images.githubusercontent.com/6397875/232090951-7c5cdc0e-83f6-4fa4-9f60-4fb40ab6a2cb.png)

**Comment by lmatula** [comment]
Fixed config flow
