### ISSUE TITLE
Log warning: Constant ENERGY_KILO_WATT_HOUR will be depreciated

### ISSUE THREAD

**Issue by rudibarani** [lmatula/ha_chint_pm#21]
Hi. I just saw a warning messing in the logs that the constant ENERGY_KILO_WATT_HOUR needs to be updated some time this year. As I did not see a GitHub issue so far, I thought I'd let you now about this. 
Thanks for taking care and have a nice week 

- name: homeassistant.const level: WARNING message: >- ENERGY_KILO_WATT_HOUR was used from chint_pm, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'chint_pm' custom integration

**Comment by lmatula** [comment]
Fixed in branch 0.0.5
