### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by Katoche690** [lmatula/ha_chint_pm#25]
Hello, 
I don't can add my power meter DTSU666 I have "error unknown"

See 
![image](https://github.com/user-attachments/assets/de93a530-806b-4c33-9829-4d4c0d134515)

Thank you for your work

**Comment by lmatula** [comment]
please attach full log

**Comment by Katoche690** [comment]
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.chint_pm.config_flow
Source: custom_components/chint_pm/config_flow.py:252
intégration: Chint powermeter DTSU-666-h (documentation)
S'est produit pour la première fois: 6 octobre 2024 à 22:08:06 (5 occurrences)
Dernier enregistrement: 22:16:22

Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
Traceback (most recent call last):
  File "/config/custom_components/chint_pm/config_flow.py", line 252, in async_step_setup_serial
    info = await validate_serial_setup(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chint_pm/config_flow.py", line 91, in validate_serial_setup
    rr = client.read_holding_registers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/mixin.py", line 107, in read_holding_registers
    return self.execute(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 396, in execute
    return self.transaction.execute(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 180, in execute
    response, last_exception = self._transact(
                               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 327, in _transact
    result = self._recv(response_length, full)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 357, in _recv
    read_min = self.client.framer.recvPacket(min_size)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/rtu_framer.py", line 235, in recvPacket
    result = self.client.recv(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 283, in recv
    self._wait_for_data()
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 272, in _wait_for_data
    time.sleep(self._recv_interval)
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep


Thank you

**Comment by Katoche690** [comment]
> please attach full log

Hello please see below >>>> 

Enregistreur: custom_components.chint_pm.config_flow
Source: custom_components/chint_pm/config_flow.py:252
intégration: Chint powermeter DTSU-666-h (documentation)
S'est produit pour la première fois: 6 octobre 2024 à 22:08:06 (5 occurrences)
Dernier enregistrement: 22:16:22

Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
Traceback (most recent call last):
File "/config/custom_components/chint_pm/config_flow.py", line 252, in async_step_setup_serial
info = await validate_serial_setup(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/chint_pm/config_flow.py", line 91, in validate_serial_setup
rr = client.read_holding_registers(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/mixin.py", line 107, in read_holding_registers
return self.execute(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 396, in execute
return self.transaction.execute(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 180, in execute
response, last_exception = self._transact(
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 327, in _transact
result = self._recv(response_length, full)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 357, in _recv
read_min = self.client.framer.recvPacket(min_size)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/rtu_framer.py", line 235, in recvPacket
result = self.client.recv(size)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 283, in recv
self._wait_for_data()
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 272, in _wait_for_data
time.sleep(self._recv_interval)
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
raise_for_blocking_call(
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep


Thank you for this help

**Comment by lmatula** [comment]
this is seems to pymodbus problem.

**Comment by Katoche690** [comment]
Do you think you can help me solve this problem?
Thank you

**Comment by Suessinger** [comment]
have you found a solution to the problem?

**Comment by DotisNet** [comment]
I fixed this issue on my side but i can't create branch or push the fix.

**Comment by Katoche690** [comment]
Oh Nice. Maybe you can share here ?

**Comment by DotisNet** [comment]
![image](https://github.com/user-attachments/assets/78186146-ba39-435f-803e-87ae8fdb266a)
![image](https://github.com/user-attachments/assets/51d11482-4f99-4d37-875b-487f1016ffd4)

**Comment by Katoche690** [comment]
The problem is already present. 

Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.chint_pm.config_flow
Source: custom_components/chint_pm/config_flow.py:252
intégration: Chint powermeter DTSU-666-h (documentation)
S'est produit pour la première fois: 10:10:47 (2 occurrences)
Dernier enregistrement: 10:10:52

Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
Traceback (most recent call last):
  File "/config/custom_components/chint_pm/config_flow.py", line 252, in async_step_setup_serial
    info = await validate_serial_setup(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chint_pm/config_flow.py", line 91, in validate_serial_setup
    rr = client.read_holding_registers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/mixin.py", line 107, in read_holding_registers
    return self.execute(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 396, in execute
    return self.transaction.execute(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 180, in execute
    response, last_exception = self._transact(
                               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 327, in _transact
    result = self._recv(response_length, full)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 357, in _recv
    read_min = self.client.framer.recvPacket(min_size)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/rtu_framer.py", line 235, in recvPacket
    result = self.client.recv(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 283, in recv
    self._wait_for_data()
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 272, in _wait_for_data
    time.sleep(self._recv_interval)
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep

**Comment by lmatula** [comment]
i still think this is pymodbus lib issue. try updating the minimum version in manifest.json:
https://github.com/lmatula/ha_chint_pm/blob/ea002ee92d24b9f860eba3cf9da8733f4d96bfb4/custom_components/chint_pm/manifest.json#L7

**Comment by DotisNet** [comment]
> The problem is already present.
> 
> Cette erreur provient d'une intégration personnalisée
> 
> Enregistreur: custom_components.chint_pm.config_flow Source: custom_components/chint_pm/config_flow.py:252 intégration: Chint powermeter DTSU-666-h (documentation) S'est produit pour la première fois: 10:10:47 (2 occurrences) Dernier enregistrement: 10:10:52
> 
> Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep Traceback (most recent call last): File "/config/custom_components/chint_pm/config_flow.py", line 252, in async_step_setup_serial info = await validate_serial_setup( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/chint_pm/config_flow.py", line 91, in validate_serial_setup rr = client.read_holding_registers( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/client/mixin.py", line 107, in read_holding_registers return self.execute( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 396, in execute return self.transaction.execute(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 180, in execute response, last_exception = self._transact( ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 327, in _transact result = self._recv(response_length, full) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py", line 357, in _recv read_min = self.client.framer.recvPacket(min_size) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/rtu_framer.py", line 235, in recvPacket result = self.client.recv(size) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 283, in recv self._wait_for_data() File "/usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py", line 272, in _wait_for_data time.sleep(self._recv_interval) File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func raise_for_blocking_call( File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call raise RuntimeError( RuntimeError: Caught blocking call to sleep with args (0.004166666666666667,) inside the event loop by custom integration 'chint_pm' at custom_components/chint_pm/config_flow.py, line 91: rr = client.read_holding_registers(. (offender: /usr/local/lib/python3.12/site-packages/pymodbus/client/serial.py, line 272: time.sleep(self._recv_interval)), please report it to the author of the 'chint_pm' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep

il te manque les await ici :  rr = client.read_holding_registers ca devrait être comme sur mon screen :  rr = await client.read_holding_registers
