### ISSUE TITLE
Support for DDSU-666 (1phase?)

### ISSUE THREAD

**Issue by udochrist** [lmatula/ha_chint_pm#28]
Hi,

are there any plans to also support the CHINT DDSU 666 single phase power meter ?

regards
Udo

**Comment by lmatula** [comment]
hi
Yes, i'm planning, but not have enough time currently.

**Comment by udochrist** [comment]
Ok. I’ve simply used the default modbus Integration and created the entities via yaml. Only drawback is that they are not grouped as a device. Otherwise it’s working Fine.
