### ISSUE TITLE
how to install your integration

### ISSUE THREAD

**Issue by tomasvida** [lmatula/ha_chint_pm#3]
Hi, can you help me  please with instalation your integration to home assistant? 

Many thanks
tomas

**Comment by lmatula** [comment]
Hi, in hacs plugin add custom repo with this repo url:
[https://hacs.xyz/docs/faq/custom_repositories/](url)

That after you can find in add new integration

**Comment by tomasvida** [comment]
Thank you for link, but, not working... 
https://github.com/lmatula/ha_chint_pm/
it is also wrong.. :-(
