### ISSUE TITLE
Modbus to TCP

### ISSUE THREAD

**Issue by zelphir** [lmatula/ha_chint_pm#5]
It would be nice to provide a guide on how to connect the meter. Are you using ESP32 + RS485? Or other things?

**Comment by lmatula** [comment]
I'm connecting with an Elfin ee11 [Aliexpress](https://www.aliexpress.com/item/4000843861682.html?spm=a2g0o.detail.1000060.1.64b53504ABqVe0&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.291025.0&scm_id=1007.13339.291025.0&scm-url=1007.13339.291025.0&pvid=dfebba9a-afe4-4774-a650-009a7f60688e&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.291025.0,pvid:dfebba9a-afe4-4774-a650-009a7f60688e,tpp_buckets:668%232846%238112%231997&pdp_npi=3%40dis%21HUF%214105.94%213204.12%21%21%21%21%21%402103243416862253898008885eb117%2110000009110323840%21rec%21HU%21191105467) or use [ew11](https://www.aliexpress.com/item/32915964545.html?spm=a2g0o.detail.1000060.1.2c9d665fNEm4aT&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.291025.0&scm_id=1007.13339.291025.0&scm-url=1007.13339.291025.0&pvid=cef2e463-0c93-4667-9fd0-d454639b30ed&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.291025.0,pvid:cef2e463-0c93-4667-9fd0-d454639b30ed,tpp_buckets:668%232846%238112%231997&pdp_npi=3%40dis%21HUF%214123.62%213175.82%21%21%21%21%21%402103243416862253934908967eb117%2110000002274897791%21rec%21HU%21191105467)

I'm tested with usb rs485 converter.

I think theoretical esp32+RS485 is could be fine, if fits to modbus ethernet standard.

**Comment by zelphir** [comment]
so there is no need to program esp32 boards, it's a simple RS485 to ethernet
